apiVersion: v1
kind: Service
metadata:
  name: mike-employee-service
  labels:
    app: employees
spec:
  selector:
    app: employees
    component: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP