apiVersion: v1
kind: Service
metadata:
  name: employees-nodeport
  labels:
    app: employees
spec:
  selector:
    app: employees
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001