apiVersion: v1
kind: Service
metadata:
  name: mikeemployees-nodeport
spec:
  type: NodePort
  selector:
    app: employees
    component: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000