apiVersion: v1
kind: Pod
metadata:
  name: mikeemplooye-pod
  labels:
    app: employees
    component: frontend
spec:
  imagePullSecrets:
    - name: mikek8 
  containers:
    - name: mikeemployees
      image: 108157356054.dkr.ecr.us-east-1.amazonaws.com/ecr_my_app:dacbbba
      imagePullPolicy: Always
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      env:
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mysql-root-password
              key: MYSQL_ROOT_PASSWORD
        - name: DBPORT
          value: "3306"
        - name: DBHOST
          value: " 10.244.0.5"
        - name: DBUSER
          value: "root"
      ports:
        - containerPort: 8080

